<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="05068-020L" name="testCases.TS_001_Sales_Planning" tests="25" failures="4" timestamp="16 Apr 2019 06:03:38 GMT" time="19.551" errors="2">
  <testcase name="TC_012_VerifyIs_GNDivisions_DropdownEnabled" time="0.038" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_008_Verify_Tower_Lable" time="0.133" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_017_select_Terriotorry" time="0.972" classname="testCases.TS_001_Sales_Planning">
    <failure type="java.lang.AssertionError" message="expected [AWI - Awissawella Depot] but found [COL - Colombo Depot
 ]">
      <![CDATA[java.lang.AssertionError: expected [AWI - Awissawella Depot] but found [COL - Colombo Depot
 ]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at proxy.verifications.verifyGlobalSelectDropDown(verifications.java:122)
	at pages.SalesPlanningPage.verifySelectedTerriotarry(SalesPlanningPage.java:180)
	at testCases.TS_001_Sales_Planning.TC_017_select_Terriotorry(TS_001_Sales_Planning.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_017_select_Terriotorry -->
  <testcase name="TC_018_Verify_select_GN_Division" time="2.320" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_0014_verifyDistrictvalues" time="0.548" classname="testCases.TS_001_Sales_Planning">
    <error type="java.lang.ArrayIndexOutOfBoundsException" message="9">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 9
	at proxy.verifications.verifyAllDropdownValues(verifications.java:54)
	at pages.DshboardPage.verifyAllTheDistrictdropdownValues(DshboardPage.java:202)
	at testCases.TS_001_Sales_Planning.TC_0014_verifyDistrictvalues(TS_001_Sales_Planning.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TC_0014_verifyDistrictvalues -->
  <testcase name="TC_025_districtValue" time="0.104" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_003_Verify_District_Lable" time="0.107" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_005_Verify_GnDivision_Lable" time="0.053" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_024_verify_SubmitSuccessFully" time="3.404" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_010_VerifyIs_District_DropdownEnabled" time="0.137" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_009_Verify_Remarks_Lable" time="0.058" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_007_Verify_EndDate_Lable" time="0.170" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_020_verify_select_EndDate" time="0.493" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_004_Verify_TerriTory_Lable" time="0.054" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_021_verify_Click_tower_Check_Box" time="0.266" classname="testCases.TS_001_Sales_Planning">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at org.testng.Assert.assertFalse(Assert.java:73)
	at proxy.verifications.ClickonCheckBox(verifications.java:170)
	at pages.SalesPlanningPage.ClickonToweCheckBox(SalesPlanningPage.java:254)
	at testCases.TS_001_Sales_Planning.TC_021_verify_Click_tower_Check_Box(TS_001_Sales_Planning.java:161)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_021_verify_Click_tower_Check_Box -->
  <testcase name="TC_016_verifyTerritoryvalues" time="0.693" classname="testCases.TS_001_Sales_Planning">
    <error type="java.lang.ArrayIndexOutOfBoundsException" message="4">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 4
	at proxy.verifications.verifyAllDropdownValues(verifications.java:54)
	at pages.DshboardPage.verifyAllTheTerritorrdropdownValues(DshboardPage.java:210)
	at testCases.TS_001_Sales_Planning.TC_016_verifyTerritoryvalues(TS_001_Sales_Planning.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TC_016_verifyTerritoryvalues -->
  <testcase name="TC_001_Verify_navigateTo_SalesPlanning" time="6.476" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_006_Verify_StartDate_Lable" time="0.110" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_011_VerifyIs_Territory_DropdownEnabled" time="0.064" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_013_VerifyIs_Towers_DropdownEnabled" time="0.077" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_019_verify_select_StarttDate" time="0.624" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="close" time="0.001" classname="testCases.TS_001_Sales_Planning"/>
  <testcase name="TC_022_verify_Confirm_message" time="1.001" classname="testCases.TS_001_Sales_Planning">
    <failure type="java.lang.AssertionError" message="expected [Are you sure you need to assign this task to Chamodi Wijewardana ?] but found [Are you sure you need to assign this task to Supun Senerath ?]">
      <![CDATA[java.lang.AssertionError: expected [Are you sure you need to assign this task to Chamodi Wijewardana ?] but found [Are you sure you need to assign this task to Supun Senerath ?]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at proxy.verifications.VerifyTextgloble(verifications.java:30)
	at pages.SalesPlanningPage.VerifyTextMessage(SalesPlanningPage.java:270)
	at testCases.TS_001_Sales_Planning.TC_022_verify_Confirm_message(TS_001_Sales_Planning.java:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_022_verify_Confirm_message -->
  <testcase name="TC_023_verify_Cancle_Submission" time="0.386" classname="testCases.TS_001_Sales_Planning">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at org.testng.Assert.assertFalse(Assert.java:73)
	at pages.SalesPlanningPage.ClickOnCancleButton(SalesPlanningPage.java:290)
	at testCases.TS_001_Sales_Planning.TC_023_verify_Cancle_Submission(TS_001_Sales_Planning.java:183)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_023_verify_Cancle_Submission -->
  <testcase name="TC_015_select_districtValue" time="1.262" classname="testCases.TS_001_Sales_Planning"/>
</testsuite> <!-- testCases.TS_001_Sales_Planning -->
