<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="05068-020L" name="Default test" tests="16" failures="4" timestamp="17 Apr 2019 04:53:53 GMT" time="11.399" errors="0">
  <testcase name="TC_001_Verify_Navigate_TO_Territorry_Manager_Task" time="7.283" classname="testCases.TS_003_TerritorryManagerTasks"/>
  <testcase name="TC_002_verify_User" time="0.094" classname="testCases.TS_003_TerritorryManagerTasks"/>
  <testcase name="TC_003_verifNamw_Of_The_Page" time="0.042" classname="testCases.TS_003_TerritorryManagerTasks"/>
  <testcase name="TC_004_verify_Start_From_Date_Text" time="0.044" classname="testCases.TS_003_TerritorryManagerTasks"/>
  <testcase name="TC_005_verify_End_Date_text" time="0.041" classname="testCases.TS_003_TerritorryManagerTasks"/>
  <testcase name="TC_006_verify_Territory_Text" time="0.052" classname="testCases.TS_003_TerritorryManagerTasks"/>
  <testcase name="TC_007_verify_Status_Text" time="0.044" classname="testCases.TS_003_TerritorryManagerTasks"/>
  <testcase name="TC_008_verif_OnlyExpiredTsks_Text" time="0.05" classname="testCases.TS_003_TerritorryManagerTasks">
    <failure type="java.lang.AssertionError" message="expected [Only expired tasks] but found []">
      <![CDATA[java.lang.AssertionError: expected [Only expired tasks] but found []
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at pages.TerritorryManagerTasks.VerifyText(TerritorryManagerTasks.java:123)
	at pages.TerritorryManagerTasks.OnlyExpiredTaskText(TerritorryManagerTasks.java:172)
	at testCases.TS_003_TerritorryManagerTasks.TC_008_verif_OnlyExpiredTsks_Text(TS_003_TerritorryManagerTasks.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_008_verif_OnlyExpiredTsks_Text -->
  <testcase name="TC_009_verif_EnerStarDate" time="0.524" classname="testCases.TS_003_TerritorryManagerTasks"/>
  <testcase name="TC_010_verif_EnerEndDate" time="0.448" classname="testCases.TS_003_TerritorryManagerTasks"/>
  <testcase name="TC_011_verif_SelectTerritoryValue" time="1.042" classname="testCases.TS_003_TerritorryManagerTasks">
    <failure type="java.lang.AssertionError" message="expected [AWI - Awissawella Depot] but found [AWI - Awissawella Depot
 ]">
      <![CDATA[java.lang.AssertionError: expected [AWI - Awissawella Depot] but found [AWI - Awissawella Depot
 ]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at proxy.verifications.verifyGlobalSelectDropDown(verifications.java:122)
	at pages.TerritorryManagerTasks.selectTerritoryValueFromDropdown(TerritorryManagerTasks.java:214)
	at testCases.TS_003_TerritorryManagerTasks.TC_011_verif_SelectTerritoryValue(TS_003_TerritorryManagerTasks.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_011_verif_SelectTerritoryValue -->
  <testcase name="verify_all_values_in_the_DD" time="0.477" classname="testCases.TS_003_TerritorryManagerTasks">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="11">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 11
	at proxy.verifications.verifyAllDropdownValues(verifications.java:54)
	at pages.TerritorryManagerTasks.verifyallTerritorryDDValues(TerritorryManagerTasks.java:258)
	at testCases.TS_003_TerritorryManagerTasks.verify_all_values_in_the_DD(TS_003_TerritorryManagerTasks.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verify_all_values_in_the_DD -->
  <testcase name="TC_012_verif_selectStatusValue" time="0.375" classname="testCases.TS_003_TerritorryManagerTasks">
    <failure type="java.lang.AssertionError" message="expected [ASSIGNED] but found [ASSIGNED
 ]">
      <![CDATA[java.lang.AssertionError: expected [ASSIGNED] but found [ASSIGNED
 ]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at pages.TerritorryManagerTasks.EnterValuesForDropdown(TerritorryManagerTasks.java:204)
	at pages.TerritorryManagerTasks.selectStatusValue(TerritorryManagerTasks.java:220)
	at testCases.TS_003_TerritorryManagerTasks.TC_012_verif_selectStatusValue(TS_003_TerritorryManagerTasks.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_012_verif_selectStatusValue -->
  <testcase name="TC_013_verif_SubmitButton" time="0.651" classname="testCases.TS_003_TerritorryManagerTasks"/>
  <testcase name="TC_014_verif_Defaultview" time="0.032" classname="testCases.TS_003_TerritorryManagerTasks"/>
  <testcase name="TC_015_verif_GridviewIsEnabled" time="0.112" classname="testCases.TS_003_TerritorryManagerTasks"/>
</testsuite> <!-- Default test -->
