<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="40082" started-at="2019-01-11T07:42:05Z" finished-at="2019-01-11T07:42:45Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="40082" started-at="2019-01-11T07:42:05Z" finished-at="2019-01-11T07:42:45Z">
      <class name="testCases.TC_ViewSubtaskList">
        <test-method status="FAIL" signature="TC001_Verify_Navigate_TO_SubtaskList()[pri:0, instance:testCases.TC_ViewSubtaskList@590c73d3]" name="TC001_Verify_Navigate_TO_SubtaskList" duration-ms="15339" started-at="2019-01-11T13:12:05Z" finished-at="2019-01-11T13:12:20Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://wom/v3staging/d2d/SubTaskList/view] but found [http://wom/v3staging/d2d/UpdateTerritoryManagers/view]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://wom/v3staging/d2d/SubTaskList/view] but found [http://wom/v3staging/d2d/UpdateTerritoryManagers/view]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at pages.DshboardPage.NavigateTOSelectSubtaskList(DshboardPage.java:79)
	at testCases.TC_ViewSubtaskList.TC001_Verify_Navigate_TO_SubtaskList(TC_ViewSubtaskList.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC001_Verify_Navigate_TO_SubtaskList -->
        <test-method status="PASS" signature="TC001_Verify_SelectDD()[pri:0, instance:testCases.TC_ViewSubtaskList@590c73d3]" name="TC001_Verify_SelectDD" duration-ms="24665" started-at="2019-01-11T13:12:20Z" finished-at="2019-01-11T13:12:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC001_Verify_SelectDD -->
      </class> <!-- testCases.TC_ViewSubtaskList -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
